# Generated by Django 2.2.6 on 2019-11-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginDetails',
            new_name='LoginDetail',
        ),
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
