# Generated by Django 2.2.6 on 2019-11-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0002_auto_20191110_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePic', models.FileField(upload_to='profilepicture/')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbapp.LoginDetail')),
            ],
        ),
    ]
